//%attributes = {"invisible":true,"shared":true}
// ----------------------------------------------------
// Project Method: Fnd_Hook_Shell_VirtualStructure

// Go to Product Sales example database to copy the example for this method
// This method was automatically generated by Foundation 5 on May 12, 2009.
// ----------------------------------------------------

